disabled = false
locale = "en"
label = "English"
weight = 2
title = "Blogus Chii"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Chius's Blog"

[params.author]
  name = "Chius"
  headline = "🥰 Welcome to my blog"