[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "归档"
  pageRef = "archives"
  weight = 20

[[main]]
  name = "碎碎念"
  pageRef = "memos"
  weight = 15

[[main]]
  name = "嘟嘟"
  pageRef = "fediverse"
  weight = 17

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30
