[[main]]
  name = "搜索"
  pageRef = "search"
  weight = 5

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "归档"
  pageRef = "archives"
  weight = 20

[[main]]
  name = "碎碎念"
  pageRef = "thoughts"
  weight = 15

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30