colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

mainSections = ["posts"]

Logo = "img/logo.png"

defaultBackgroundImage = "img/background.svg"
defaultFeaturedImage = "img/featured.svg"

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/background.svg"
  showRecent = true
  showRecentItems = 5
  showMoreLink = false
  cardView = true
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateOnlyInArticle = false
  showViews = false
  showLikes = false
  showAuthor = true
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showWordCount = true
  showPagination = true
  showTaxonomies = true
  showTags = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showHeadingAnchors = true
  showRelatedContent = true
  relatedContentLimit = 5

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  groupByYear = true
  cardView = true
  showTableOfContents = true

[taxonomy]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showTermCount = true

[term]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  groupByYear = false
  cardView = true

[memos]
  serverURL = "https://memos.chius.cc"
