baseURL = "https://blog.chius.cc/"
title = "Blogus Chii"
theme = "PaperMod"
defaultContentLanguage = "zh"
hasCJKLanguage = true

[languages.zh]
  languageCode = "zh-cn"
  contentDir = "content"
  [languages.zh.params]
    description = "Chius 的博客"
    [languages.zh.params.homeInfoParams]
      Title = "Chius"
      Content = "🥰 欢迎来到我的个人博客"
  [[languages.zh.menu.main]]
    name = "搜索"
    url = "/search/"
    weight = 5
  [[languages.zh.menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[languages.zh.menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 20
  [[languages.zh.menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 30

[languages.en]
  languageCode = "en"
  contentDir = "content/en"
  [languages.en.params]
    description = "Chius's Blog"
    [languages.en.params.homeInfoParams]
      Title = "Chius"
      Content = "🥰 Welcome to my blog"
  [[languages.en.menu.main]]
    name = "Search"
    url = "/en/search/"
    weight = 5
  [[languages.en.menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/en/posts/"
    weight = 10
  [[languages.en.menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/en/archives/"
    weight = 20
  [[languages.en.menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/en/tags/"
    weight = 30

[params]
env = "production"
author = "Chius"
defaultTheme = "light"
ShowToc = true
ShowReadingTime = true
ShowWordCount = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
disableThemeToggle = true
ShowRssButtonInSectionTermList = true
ShowCodeCopyButtons = true
smoothScroll = true
ShowFullTextinRSS = true
hideFooter = false

[params.assets]
    favicon = "/favicon.png"

[params.profileMode]
enabled = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
